CREATE TABLE contatos(
    codigo bigint generated by default as identity,
    nome VARCHAR(160) NOT NULL,
    telefone VARCHAR(16) NOT NULL,
    data_nascimento DATE NOT NULL,
    CONSTRAINT PK_CONTATOS PRIMARY KEY(codigo)
);