name: "Default Workflow"

on: [push]

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Gradle Build
        run: gradle clean assemble --parallel
  
  Test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle test
        run: gradle clean test --parallel